### ISSUE TITLE
Access manager has been derived from Telegram APIs

### ISSUE THREAD

**Issue by RayCxggg** [flynnoct/chatgpt-telegram-bot#15]
Access manager has been derived from Telegram APIs in new branch **accessmanager-dev**. Please help me test it. Thx. @flynnoct 

In case of granting users different authority between text, voice and file, the <chat_type> field is currently reserved for future use.

**Comment by flynnoct** [comment]
I refactor access manager code.
This should be handled in message manager and we should do that later. Close this issue for now.
