### ISSUE TITLE
Suggestion: Multi-User Support

### ISSUE THREAD

**Issue by dtimekeeper** [flynnoct/chatgpt-telegram-bot#20]
One of my use cases is basically running another instance for my friends to use as a telegram bot. It would be helpful to have a way to ‘whitelist’ all telegram IDs so as long as they know the link to message it, they can talk to the bot.

Related to this too, not sure how feasible it is, would be separate conversational context for each person that messages the bot, but I’m also not sure if this is even possible with the API.

**Comment by flynnoct** [comment]
I like this `allow_all_user` idea and I will implement this.

About maintain a context for each person, may I ask you why do you need this function? Why not chat with the bot privately if you want separate contexts?

**Comment by dtimekeeper** [comment]
Thank you!

So I may not be understanding the API and each bot session properly, but do
all conversations with the bot from everyone share one context thread until
it is reset? Or do they have their own context and conversation with each
telegram ID it talks with.

**Comment by flynnoct** [comment]
I think it might be a misunderstanding.

Currently, the bot will maintain contexts for each "conversation". Different users' private messages have different contexts, and different groups have different contexts. However, within the same group, they share the same context (currently the bot cannot distinguish which user is talking to it in the group).

BTW, the `/clear` command only works for current context and it will not touch any of other contexts.

**Comment by dtimekeeper** [comment]
Ah I understand now - then that is perfect already.

I think with the addition of allow_all_users, this will become a very
compelling choice for people who want to roll their own Telegram bots for
themselves AND their friends.

**Comment by flynnoct** [comment]
Implemented. Pull `dev` branch and have a try.

I strongly recommend you to create a new directory to test it, the `dev` channel code could be unstable. This feature will be released in v1.2.0.
