### ISSUE TITLE
bot not responding

### ISSUE THREAD

**Issue by emperorjoker** [flynnoct/chatgpt-telegram-bot#27]
I tried main and dev and they both have the same problem.

When using start_bot.sh, although it says bot started successfully, it cannot get a response after sending a message through Telegram Bot.

When starting telegram_message_parser.py with the python command, the following error is encountered.

`Traceback (most recent call last):
  File "/home/src/telegram_message_parser.py", line 15, in <module>
    from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, InlineQueryHandler, ChosenInlineResultHandler, ContextTypes, filters
ModuleNotFoundError: No module named 'telegram'`

**Comment by flynnoct** [comment]
Have you installed dependencies? If `pip install -r requirements.txt` is not working. Try run this manually:

```bash
pip install openai
pip install python-telegram-bot
```

If still not working, try,
```bash
pip3 install openai
pip3 install python-telegram-bot
```

Let me know if this solved your problem.

**Comment by flynnoct** [comment]
I see. Maybe try to uninstall them completely and then reinstall them. Especially `telegram` module.

`pip uninstall telegram`
`pip uninstall python-telegram-bot`

Then reinstall `python-telegram-bot`. In my experience, you are not need to install `telegram` module and it will be installed with `python-telegram-bot`.

PS: Make sure you don't have a `telegram.py` file in your workspace.

**Comment by emperorjoker** [comment]
Can I ask which minimum version of python3 is supported?

**Comment by flynnoct** [comment]
I'm not sure. I haven't run this in different envs.

My Python3 version is 3.8.10

**Comment by emperorjoker** [comment]
I reconfigured the virtual environment and this time without telegram=0.0.1 installed, the previous error disappeared, but I encountered a new error. 

I am using Debian 11 and Python 3.9.2

`python3 src/telegram_message_parser.py
Traceback (most recent call last):
  File "/home/src/telegram_message_parser.py", line 23, in <module>
    config_dict = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 22 (char 482)`

**Comment by flynnoct** [comment]
Check this https://github.com/flynnoct/chatgpt-telegram-bot/issues/13. I'm almost sure this will solve your problem.

**Comment by emperorjoker** [comment]
I adjusted the config.json, and it has worked.
