### ISSUE TITLE
[suggestion]change the key value of ChatGPT through command line

### ISSUE THREAD

**Issue by peteisacat** [flynnoct/chatgpt-telegram-bot#34]
It would be great if we could change the key value of ChatGPT through command line, such as typing (or selecting) [change key value] in the terminal, and then inputting the new key to update the key value in the configuration file, which would be more convenient than editing the config file manually.😄

**Comment by RayCxggg** [comment]
A great advice. We will try to provide a simple script for updating the `config.json` file.

**Comment by peteisacat** [comment]
> A great advice. We will try to provide a simple script for updating the `config.json` file.

many thanks 😄

**Comment by RayCxggg** [comment]
A script is added to update the config file throught command line.
