### ISSUE TITLE
Implementing an prompt

### ISSUE THREAD

**Issue by onlineversioncontrolsystem** [flynnoct/chatgpt-telegram-bot#42]
Would be very useful to have a prompt system that allows you to set the tone of the assistant.

Something that allows us to kick conversations off with some of the settings we prefer. For example I would have:

 'prompt': 'You are a helpful assistant. You always convert imperial to metric measurements and localise spelling to the United Kingdom'

**Comment by RayCxggg** [comment]
This is a coming feature in progress! Do follow the update and don't miss new releases.
