### ISSUE TITLE
Bot does not respond.

### ISSUE THREAD

**Issue by Ndh474** [flynnoct/chatgpt-telegram-bot#48]
After running the command 'bash ./bin/start_bot.sh', my terminal displays the message 'Bot has been started successfully', but when I try to chat with the bot on Telegram, it doesn't respond. How can I fix this issue?
![ảnh](https://user-images.githubusercontent.com/124461319/224033764-a0f38e95-5995-457f-bd8f-f040583b1888.png)

**Comment by RayCxggg** [comment]
Please refer to the previous issues #13, #26 and #27. And don't forget to update to the latest released version v1.2.2. If the problem can't be solved, please leave more information here for us.

**Comment by Ndh474** [comment]
After running the command 'python3 telegram_message_parser.py', my cmd looks like this. What should I do next?
![ảnh](https://user-images.githubusercontent.com/124461319/224063558-f6cf5bab-661f-40d2-a242-0e1778f417b8.png)

**Comment by RayCxggg** [comment]
It is more likely an environment problem. Try to remove `python-telegram-bot` and `telegram` package with pip, and reinstall dependencies with `pip install -r requirements.txt`.

**Comment by RayCxggg** [comment]
Can you set up your Bot in an Linux environment? Our code is tested under Ubuntu and not sure to work on Windows.

**Comment by Ndh474** [comment]
Seems quite okay, but yesterday after chatting with the bot for a while, it said, "This model's maximum context length is 4097 tokens. However, your messages resulted in 4287 tokens. Please reduce the length of the messages. Sorry, I am not feeling well. Please try again," even though my messages were quite short. However, I chatted again today and it worked fine.

**Comment by flynnoct** [comment]
> Seems quite okay, but yesterday after chatting with the bot for a while, it said, "This model's maximum context length is 4097 tokens. However, your messages resulted in 4287 tokens. Please reduce the length of the messages. Sorry, I am not feeling well. Please try again," even though my messages were quite short. However, I chatted again today and it worked fine.

That's because the ChatGPT API won't "remember" the context, and the context will be saved in bot temporarily and sent to API as "context". That's the main reason of reaching the limit. 

However, in some cases, I also noticed even if I didn't chat much with the API it will also return with this exception. So this may happen sometimes, I believe it's an API's issue, not the bot's.

**Comment by Ndh474** [comment]
Thank you for everyone's help, I will close this issue.
