### ISSUE TITLE
Add TTS feature to reply voice messages with Amazon Polly

### ISSUE THREAD

**Issue by han3on** [flynnoct/chatgpt-telegram-bot#67]
Any possible to add text-to-speech feature to the bot? For example, with Amazon Polly, we could get 5 million characters free per month for 12 months with the AWS Free Tier. `https://aws.amazon.com/polly/`

This feature could allow the bot to reply voice messages to users. This could make the bot more powerful, for example for language learning, etc.

**Comment by RayCxggg** [comment]
This feature is currently in progress!

**Comment by han3on** [comment]
> This feature is currently in progress!

Thanks.

**Comment by RayCxggg** [comment]
@han3on We are working on adding TTS feature with **Microsoft Azure**.

**Comment by han3on** [comment]
> @han3on We are working on adding TTS feature with **Microsoft Azure**. 

That sounds great. Does the dev branch work with Azure TTS?

**Comment by flynnoct** [comment]
@han3on not yet, but it will be there soon. I will leave you a message here when it's ready.🥳

**Comment by RayCxggg** [comment]
I am closing this issue because this feature is in progress.
