### ISSUE TITLE
v1.2.2 to v1.3.0. Backward compatibility

### ISSUE THREAD

**Issue by kegfire** [flynnoct/chatgpt-telegram-bot#78]
After updating from version 1.2.2 to 1.3.0, the bot stopped responding. I discovered that new parameters were added to the config.json file. The bot did not work until I added the following new parameters:
- "openai_timeout"
- "enable_custom_system_role"
- "system_role"

Perhaps default values for these parameters should be used if they do not exist.

**Comment by RayCxggg** [comment]
Highly appreciated. We will set default values to new params for better backward compatibility.

**Comment by flynnoct** [comment]
You are right. A minor update will be released soon to fix this. Thanks.

**Comment by flynnoct** [comment]
Fixed in v1.3.1, thanks again.
