### ISSUE TITLE
Error in TG lib when starting

### ISSUE THREAD

**Issue by livingfree2023** [flynnoct/chatgpt-telegram-bot#8]
I followed your procedures on an ARM based Oracle VPS but received the following error. 

> $ python3 telegram_message_parser.py
> Traceback (most recent call last):
>   File "telegram_message_parser.py", line 15, in <module>
>     from telegram import Update
> ImportError: cannot import name 'Update' from 'telegram' (/home/ubuntu/.local/lib/python3.8/site-packages/telegram/__init__.py)

I am using 3.8.10 python

> $ py --version
> Python 3.8.10

and this is the requirements:

![image](https://user-images.githubusercontent.com/125038641/222876712-2ba3c097-7b7a-4f36-b970-c92f12bcc027.png)

**Comment by flynnoct** [comment]
Congrats🎉
